image: Visual Studio 2017
platform: x64
clone_depth: 1
environment:
  CACHE: 'c:\cache\'
  SBCL_HOME: 'C:\Program Files\Steel Bank Common Lisp\2.0.1\'
  bintrayapikey:
    secure: O42a6FepgN/X3CzWpPbJkuKRhmENlIwBfbtMVQLKSWR/annp514THuh4Dynu6xLZ

install:
# Like Windows Installer, Chocolatey's build files are apparently incapable of building the sources
- ps: If(!(test-path $env:CACHE )) { mkdir $env:CACHE; }
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://beta.quicklisp.org/quicklisp.lisp" -OutFile $env:CACHE\quicklisp.lisp
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/Clozure/ccl/releases/download/v1.12/windowsx86.zip" -OutFile $env:CACHE\ccl-bootstrap.zip
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/Clozure/ccl/archive/v1.12.zip" -OutFile $env:CACHE\ccl.zip
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://gitlab.common-lisp.net/asdf/asdf/-/archive/3.3.4.4/asdf-3.3.4.4.zip"  -OutFile $env:CACHE\asdf.zip
#- ps: Invoke-WebRequest -UserAgent wget -Uri "https://downloads.sourceforge.net/project/sbcl/sbcl/2.0.1/sbcl-2.0.1-x86-64-windows-binary.msi" -OutFile $env:CACHE\sbcl.msi
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/joaotavora/sly/archive/master.zip" -OutFile "$env:CACHE\sly.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/didierverna/declt/archive/master.zip" -OutFile "$env:CACHE\declt.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/McCLIM/McCLIM/archive/master.zip" -OutFile "$env:CACHE\mcclim.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/edicl/flexi-streams/archive/master.zip" -OutFile "$env:CACHE\flexi-streams.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://gitlab.com/pouar/illogical-pathnames/-/archive/pouar/illogical-pathnames-pouar.zip" -OutFile "$env:CACHE\illogical-pathnames.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://gitlab.com/pouar/iterate/-/archive/pouar/iterate-pouar.zip" -OutFile "$env:CACHE\iterate.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/pouar/cl-marshal/archive/pouar.zip" -OutFile "$env:CACHE\marshal.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://downloads.sourceforge.net/project/dejavu/dejavu/2.37/dejavu-fonts-ttf-2.37.zip" -OutFile $env:CACHE\dejavu.zip
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/Clozure/ccl/commit/71cc1a5a59bff33dd577a8b9c3761f7e0f179848.patch" -OutFile $env:CACHE\71cc1a5a59bff33dd577a8b9c3761f7e0f179848.patch
#- cmd: 'C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --packages texinfo-tex,texlive-collection-xetex,jq,patch,make,m4,mingw64-x86_64-binutils,mingw64-x86_64-gcc-core,mingw64-x86_64-headers,mingw64-x86_64-pthreads,mingw64-x86_64-runtime'
- cmd: 'C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --packages jq,patch,make,m4,mingw64-x86_64-binutils,mingw64-x86_64-gcc-core,mingw64-x86_64-headers,mingw64-x86_64-pthreads,mingw64-x86_64-runtime'
- ps: Expand-Archive $env:CACHE\ccl.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\ccl-bootstrap.zip -DestinationPath $env:CACHE
- ps: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\common-lisp\
- ps: Expand-Archive $env:CACHE\asdf.zip -DestinationPath $env:USERPROFILE\common-lisp\
- ps: Expand-Archive $env:CACHE\sly.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\declt.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\mcclim.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\dejavu.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\illogical-pathnames.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\iterate.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\flexi-streams.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\marshal.zip -DestinationPath $env:CACHE
- ps: Copy-Item $env:CACHE\win64-headers\ -recurse -destination $env:CACHE\ccl-1.12\
- ps: Copy-Item $env:CACHE\wx86cl64.image -destination $env:CACHE\ccl-1.12\
- ps: Copy-Item $env:CACHE\dejavu-fonts-ttf-2.37\ttf\*.ttf  -destination C:\Windows\Fonts
- cmd:  refreshenv
- cmd: 'start /wait msiexec /i %CACHE%\sbcl.msi /quiet /qn /norestart /log sbcl-install.log'
- cmd: 'C:\cygwin64\bin\bash.exe -lc "/cygdrive/c/projects/yadfa/ci/build-ccl.sh /cygdrive/c/cache/ccl-1.12"'
- cmd: '"%CACHE%\ccl-1.12\wx86cl64.exe" -b -l "%CACHE%\quicklisp.lisp" -e "(quicklisp-quickstart:install)" -e "(ql:quickload (list :fiveam :fiveam-asdf))" -e "(uiop:quit)"'
- ps: Copy-Item ci\ccl-init.lisp -Destination $env:USERPROFILE\ccl-init.lisp
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\yadfa -ItemType SymbolicLink -Value $pwd
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\sly -ItemType SymbolicLink -Value $env:CACHE\sly-master
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\flexi-streams -ItemType SymbolicLink -Value $env:CACHE\flexi-streams-master
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\declt -ItemType SymbolicLink -Value $env:CACHE\declt-master
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\McCLIM -ItemType SymbolicLink -Value $env:CACHE\McCLIM-master
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\illogical-pathnames -ItemType SymbolicLink -Value $env:CACHE\illogical-pathnames-pouar
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\iterate -ItemType SymbolicLink -Value $env:CACHE\iterate-pouar
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\cl-marshal -ItemType SymbolicLink -Value $env:CACHE\cl-marshal-pouar
- cmd: 'C:\cygwin64\bin\bash.exe -lc "patch -d /cygdrive/c/cache/McCLIM-master -p1 -i /cygdrive/c/projects/yadfa/flatpak/0001-Listener-remove-cl-fad-dependency.patch"'
build_script:
#- cmd: '"C:\Program Files\Steel Bank Common Lisp\2.0.1\sbcl" --script "appveyor-build-docs.lisp" texi'
#- cmd: 'C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/yadfa/docs/reference;make -j4 all"'
- cmd: '"%CACHE%\ccl-1.12\wx86cl64.exe" -b -l appveyor-build.lisp -- immutable'
- ps: cp chocolatey/yadfa.nuspec yadfa.nuspec # for some reason Chocolatey seems to expect the package build file to be in the same directory as the source directory
- ps: choco pack yadfa.nuspec --version $(Get-Date -UFormat "0.9.%s")
- ps: ./yadfa test
artifacts:
- path: yadfa*.nupkg
  name: NuPKG
test_script:
- ps: |
    If(!(test-path C:\projects\yadfa\yadfa.exe )) { echo "yadfa.exe was not built";exit 1; }
    Else { echo "yadfa.exe was built"; }
    #If(!(test-path C:\projects\yadfa\docs\reference\yadfa-reference.html )) { echo "yadfa-reference.html was not built";exit 1; }
    #Else { echo "yadfa-reference.html was built"; }
    #If(!(test-path C:\projects\yadfa\docs\reference\yadfa-reference.pdf )) { echo "yadfa-reference.pdf was not built";exit 1; }
    #Else { echo "yadfa-reference.pdf was built"; }
    #If(!(test-path C:\projects\yadfa\docs\reference\yadfa-reference.info )) { echo "yadfa-reference.info was not built";exit 1; }
    #Else { echo "yadfa-reference.info was built"; }
    #If(!(test-path C:\projects\yadfa\docs\reference\yadfa-reference.ps )) { echo "yadfa-reference.ps was not built";exit 1; }
    #Else { echo "yadfa-reference.ps was built"; }
    #If(!(test-path C:\projects\yadfa\docs\reference\yadfa-reference.dvi )) { echo "yadfa-reference.dvi was not built";exit 1; }
    #Else { echo "yadfa-reference.dvi was built"; }
    #If(!(test-path C:\projects\yadfa\docs\reference\yadfa-reference.xml )) { echo "yadfa-reference.xml was not built";exit 1; }
    #Else { echo "yadfa-reference.xml was built"; }
    If(!(Get-ChildItem C:\projects\yadfa\yadfa*.nupkg )) { echo "nupkg was not built";exit 1; }
    Else { echo "nupkg was built"; }
deploy_script:
- ps: |
    if( $env:APPVEYOR_REPO_BRANCH -like "master") {
        nuget sources Add -Name Bintray -Source https://api.bintray.com/nuget/pouar/yadfa-chocolatey -UserName pouar -Password $env:bintrayapikey
        nuget setapikey 'pouar:'$env:bintrayapikey -Source Bintray
        nuget push $([string[]](Get-Item yadfa*.nupkg)) -Source https://api.bintray.com/nuget/pouar/yadfa-chocolatey
    }
- cmd: 'C:\cygwin64\bin\bash.exe -lc "export bintrayapikey APPVEYOR_REPO_BRANCH;/cygdrive/c/projects/yadfa/ci/clear-old-versions.sh"'
