image: Visual Studio 2017
platform: x64
clone_depth: 1
environment:
  CACHE: 'c:\cache\'
  SBCL_HOME: 'C:\Program Files\Steel Bank Common Lisp\1.4.2\'

install:
    - ps: If(!(test-path $env:CACHE )) { mkdir $env:CACHE; }
    - ps: Invoke-WebRequest -UserAgent wget -Uri "https://beta.quicklisp.org/quicklisp.lisp" -OutFile $env:CACHE\quicklisp.lisp
    - ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-windowsx86.zip" -OutFile $env:CACHE\ccl.zip
    - ps: Invoke-WebRequest -UserAgent wget -Uri "https://gitlab.common-lisp.net/asdf/asdf/-/archive/3.3.2.9/asdf-3.3.2.9.zip"  -OutFile $env:CACHE\asdf.zip
    - ps: Invoke-WebRequest -UserAgent wget -Uri "https://superb-sea2.dl.sourceforge.net/project/sbcl/sbcl/1.4.2/sbcl-1.4.2-x86-64-windows-binary.msi" -OutFile $env:CACHE\sbcl.msi
    - ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/joaotavora/sly/archive/master.zip" -OutFile "$env:CACHE\sly.zip"
    - ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/didierverna/declt/archive/master.zip" -OutFile "$env:CACHE\declt.zip"
    - ps: Expand-Archive $env:CACHE\ccl.zip -DestinationPath $env:CACHE
    - ps: Expand-Archive $env:CACHE\asdf.zip -DestinationPath $env:CACHE
    - ps: Expand-Archive $env:CACHE\sly.zip -DestinationPath $env:CACHE
    - ps: Expand-Archive $env:CACHE\declt.zip -DestinationPath $env:CACHE
    - cmd: 'C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm texinfo"'
    - cmd: 'start /wait msiexec /i %CACHE%\sbcl.msi /quiet /qn /norestart /log sbcl-install.log'
    - ps: Copy-Item $env:CACHE\asdf-3.3.2.9\ -recurse -destination $env:USERPROFILE\common-lisp\
    - cmd: '"%CACHE%\ccl\wx86cl64.exe" -b -l "%CACHE%\quicklisp.lisp" -e "(quicklisp-quickstart:install)"  -e "(#__exit 0)"'
    - ps: Copy-Item ci\ccl-init.lisp -Destination $env:USERPROFILE\ccl-init.lisp
    - ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\yadfa -ItemType SymbolicLink -Value $pwd
    - ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\sly -ItemType SymbolicLink -Value $env:CACHE\sly-master
    - ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\declt -ItemType SymbolicLink -Value $env:CACHE\declt-master

build_script:
    - cmd: '"C:\Program Files\Steel Bank Common Lisp\1.4.2\sbcl" --script "appveyor-build-docs.lisp" texi'
    - cmd: 'C:\msys64\usr\bin\bash.exe -lc "cd /c/projects/yadfa;makeinfo --no-split --css-include=style-common.css --css-include=style-single.css --html ./yadfa.texi"'
    - cmd: '"%CACHE%\ccl\wx86cl64.exe" -b -l appveyor-build.lisp -e "(#__exit 0)"'
    - ps: 7z a -t7z -mmt=1 -mx=9 -m0=LZMA2:d=200M:fb=273 '-x!.*' yadfa.7z .
artifacts:
    - path: yadfa.7z
      name: yadfa.7z
test_script:
    - ps: |
            If(!(test-path C:\projects\yadfa\yadfa.exe )) { exit 1 }
            If(!(test-path C:\projects\yadfa\yadfa.html )) { exit 1 }
            If(!(test-path C:\projects\yadfa\yadfa.7z )) { exit 1 }
deploy:
    - provider: BinTray
      username: pouar
      api_key:
          secure: F9a/ovGdrNBCv734A6okyGjBiCk3ByYE3wJ7j7ACbIJEhG9anJP1l6Kxs3BYQtEV
      subject: pouar
      repo: yadfa
      package: yadfa
      artifact: yadfa.7z
      version: latest
      publish: true
      override: true
      on:
          branch: master
