image: Visual Studio 2017
platform: x64
clone_depth: 1
environment:
  CACHE: 'c:\cache\'
  SBCL_HOME: 'C:\Program Files\Steel Bank Common Lisp\1.4.2\'

install:
- ps: If(!(test-path $env:CACHE )) { mkdir $env:CACHE; }
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://beta.quicklisp.org/quicklisp.lisp" -OutFile $env:CACHE\quicklisp.lisp
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-windowsx86.zip" -OutFile $env:CACHE\ccl.zip
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://gitlab.common-lisp.net/asdf/asdf/-/archive/3.3.2.13/asdf-3.3.2.13.zip"  -OutFile $env:CACHE\asdf.zip
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://downloads.sourceforge.net/project/sbcl/sbcl/1.4.2/sbcl-1.4.2-x86-64-windows-binary.msi" -OutFile $env:CACHE\sbcl.msi
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/joaotavora/sly/archive/master.zip" -OutFile "$env:CACHE\sly.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/didierverna/declt/archive/master.zip" -OutFile "$env:CACHE\declt.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://github.com/McCLIM/McCLIM/archive/master.zip" -OutFile "$env:CACHE\mcclim.zip"
- ps: Invoke-WebRequest -UserAgent wget -Uri "https://downloads.sourceforge.net/project/dejavu/dejavu/2.37/dejavu-fonts-ttf-2.37.zip" -OutFile $env:CACHE\dejavu.zip
- ps: Expand-Archive $env:CACHE\ccl.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\asdf.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\sly.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\declt.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\mcclim.zip -DestinationPath $env:CACHE
- ps: Expand-Archive $env:CACHE\dejavu.zip -DestinationPath $env:CACHE
- ps: Copy-Item $env:CACHE\dejavu-fonts-ttf-2.37\ttf\*.ttf  -destination C:\Windows\Fonts
- ps: choco install -y miktex
- cmd:  refreshenv
- cmd: 'start /wait msiexec /i %CACHE%\sbcl.msi /quiet /qn /norestart /log sbcl-install.log'
- ps: Copy-Item $env:CACHE\asdf-3.3.2.13\ -recurse -destination $env:USERPROFILE\common-lisp\
- cmd: '"%CACHE%\ccl\wx86cl64.exe" -b -l "%CACHE%\quicklisp.lisp" -e "(quicklisp-quickstart:install)"  -e "(#__exit 0)"'
- ps: Copy-Item ci\ccl-init.lisp -Destination $env:USERPROFILE\ccl-init.lisp
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\yadfa -ItemType SymbolicLink -Value $pwd
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\sly -ItemType SymbolicLink -Value $env:CACHE\sly-master
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\declt -ItemType SymbolicLink -Value $env:CACHE\declt-master
- ps: New-Item -Path $env:USERPROFILE\quicklisp\local-projects\McCLIM -ItemType SymbolicLink -Value $env:CACHE\McCLIM-master

build_script:
- cmd: '"C:\Program Files\Steel Bank Common Lisp\1.4.2\sbcl" --script "appveyor-build-docs.lisp" texi'
- cmd: 'C:\msys64\usr\bin\bash.exe -lc "export PDFTEX=xetex PDFLATEX=xelatex;cd /c/projects/yadfa;makeinfo --no-split --css-include=style-common.css --css-include=style-single.css --html ./yadfa.texi;makeinfo --no-split --pdf ./yadfa.texi;makeinfo --no-split ./yadfa.texi"'
- cmd: '"%CACHE%\ccl\wx86cl64.exe" -b -l appveyor-build.lisp -e "(#__exit 0)"'
- ps: 7z a -t7z -mmt=2 -mx=9 -m0=LZMA2:d=200M:fb=273:mc=1000000000 '-x!yadfa/*.aux' '-x!yadfa/*.cps' '-x!yadfa/*.fns' '-x!yadfa/*.vrs' '-x!yadfa/*.tps' '-x!yadfa/*.cp' '-x!yadfa/*.fn' '-x!yadfa/*.vr' '-x!yadfa/*.tp' '-x!yadfa/*.toc' '-x!yadfa/*.log' '-x!yadfa/.*' '-x!yadfa/ci' '-x!yadfa/yadfa.7z' '-x!yadfa/appveyor-build*.lisp' yadfa.7z $PWD
artifacts:
- path: yadfa.7z
  name: yadfa.7z
test_script:
- ps: |
    If(!(test-path C:\projects\yadfa\yadfa.exe )) { echo "yadfa.exe was not built";exit 1; }
    Else { echo "yadfa.exe was built"; }
    If(!(test-path C:\projects\yadfa\yadfa.html )) { echo "yadfa.html was not built";exit 1; }
    Else { echo "yadfa.html was built"; }
    If(!(test-path C:\projects\yadfa\yadfa.pdf )) { echo "yadfa.pdf was not built";exit 1; }
    Else { echo "yadfa.pdf was built"; }
    If(!(test-path C:\projects\yadfa\yadfa.info )) { echo "yadfa.info was not built";exit 1; }
    Else { echo "yadfa.info was built"; }
    If(!(test-path C:\projects\yadfa\yadfa.7z )) { echo "yadfa.7z was not built";exit 1; }
    Else { echo "yadfa.7z was built"; }
deploy:
- provider: BinTray
  username: pouar
  api_key:
    secure: O42a6FepgN/X3CzWpPbJkuKRhmENlIwBfbtMVQLKSWR/annp514THuh4Dynu6xLZ
  subject: pouar
  repo: yadfa-generic
  package: win64
  version: latest
  artifact: yadfa.7z
  publish: true
  override: true
  on:
    branch: master
