image: fedora:latest

pages:
  only:
    - master
  before_script:
    - tar -xf cache.tar || true
  script:
    - dnf -y upgrade
    - dnf -y install flatpak flatpak-builder git xz lzip bzip2 librsvg2
    - gdk-pixbuf-query-loaders-64 > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak-builder --install-deps-from=flathub --force-clean build flatpak/net.pouar.yadfa.yml
    - flatpak build-export public build
    - flatpak build-update-repo --prune-depth=10 --prune --generate-static-deltas public
  after_script:
    - tar -cf cache.tar .flatpak-builder public
  environment:
    name: production
  artifacts:
    paths:
    - public
  cache:
    paths:
      - cache.tar

test:
  except:
    - master
  script:
    - dnf -y upgrade
    - dnf -y install flatpak flatpak-builder git xz lzip bzip2 librsvg2
    - gdk-pixbuf-query-loaders-64 > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak-builder --install-deps-from=flathub --force-clean build flatpak/net.pouar.yadfa.yml

