image: fedora:latest

pages:
  only:
    - master
  before_script:
    - tar -xf cache.tar || true
  script:
    - dnf -y upgrade
    - dnf -y install flatpak flatpak-builder gnupg git xz lzip bzip2 librsvg2
    - gdk-pixbuf-query-loaders-64 > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
    - printf '%s' "$GPGKEY"|base64 -d|gpg --import
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak-builder --install-deps-from=flathub --disable-rofiles-fuse --force-clean build flatpak/net.pouar.yadfa.yml
    - flatpak build-export --gpg-sign='15BE14266E04C2E3D823DBA86FDC5B86389100FD!' public build
    - flatpak build-update-repo --gpg-sign='15BE14266E04C2E3D823DBA86FDC5B86389100FD!' --prune-depth=5 --prune --generate-static-deltas public
  after_script:
    - tar -cf cache.tar .flatpak-builder public
  environment:
    name: production
  artifacts:
    paths:
    - public
  cache:
    paths:
      - cache.tar
